[phases.setup]
cmds = [
    # Install frontend dependencies
    "cd client && npm install",
    # Install backend dependencies
    "cd server && npm install",
]

[phases.build]
cmds = [
    # Build React app
    "cd client && npm run build",
]

[start]
# Run your Node.js server
cmd = "cd server && node server.js"  # Adjust if your entry file is different